server:
  port: 8080

spring:
  application:
    name: zona-pos-backend

  datasource:
    url: jdbc:postgresql://127.0.0.1:5433/zona_pos_db
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

app:
  jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970337336763979244226452948404D6351655468576D5A7134743777217A25432A
    owner-manager-expiration-ms: 3600000 # 1 jam
    cashier-expiration-ms: 86400000      # 24 jam (1 hari)
